image: python:3.8

stages:
    - build
    - test
    - deploy

build:
  before_script:
  - apt-get update -qy
  - apt-get install -y python3 python3-pip
  - pip3 install -r requirements.txt

test:
  script:
  - pip3 manage.py makemigrations
  - pip3 manage.py migrate

deploy:
  script:
  - pip3 manage.py runserver
