image: python:3.6

stages:
    - build
    - deploy

variables:
  VIRTUAL_ENV: .env

before_script:
  - apt-get update -qy
  - apt-get install -y python3 python3-pip

build:
  stage: build
    - virtualenv $VIRTUAL_ENV
    - source $VIRTUAL_ENV/bin/activate
    - pip install -r requirements.txt

test:
  script: deploy
    - pip3 manage.py makemigrations
    - pip3 manage.py migrate
    - pip3 manage.py runserver
