image: python:3.6

stages:
    - build
    - deploy

build:
  stage: build
    - apt-get update -qy
    - apt-get install -y python3 python3-pip
    - pip3 install -r requirements.txt

test:
  script: deploy
    - pip3 manage.py makemigrations
    - pip3 manage.py migrate
    - pip3 manage.py runserver
