# Generated by Django 4.2.2 on 2023-06-28 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminface', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apps',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
