# Generated by Django 4.2.2 on 2023-06-28 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminface', '0002_alter_apps_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apps',
            name='logo',
            field=models.ImageField(upload_to='static/logos/'),
        ),
    ]
