openapi: 3.0.0
info:
  title: NGL Django Project Open API Documentation
  version: 1.0.0
  contact:
    name: Lokesh Singh Rajwar
    email: lokeshrajwar@gmail.com
    
  description: An API for a web app creating as part of recruitment process. The API allows user to get list of all the apps registeered inthe site, list of apps the user have registered till now and list of pending apps for the user.
    <h2> ER Diagram </h2>
    <h4>can be viewed in the following link</h4>
    <img src="https://https://lucid.app/documents/embedded/c3a10960-d767-4e53-9292-5167f9bd9d61?invitationId=inv_817cf038-a113-4f73-9955-570c07bee011#" />
    
  
    
    <h2> Error Code </h2>
    <table>
      <thead>
        <th> Resource </th>
        <th> Error Code </th>
        <th> Message </th>
      </thead>
      <tbody>
        <tr>
          <td> user </td>
          <td> U1001 </td>
          <td> username is required </td>
        </tr>
        <tr>
          <td> user </td>
          <td> U1002 </td>
          <td> user not found </td>
        </tr>
      </tbody>
    </table>
  
  
  
servers:
  - url: https://ngl-project.azurewebsites.net
    description: Azure server
    
  - url: http://127.0.0.1:8000
    description: Local server
  
  
  
tags:
    
  - name: apps
    description: GET operations on all apps
    
  - name: user_apps
    description: GET operations on individual user apps
    
  

paths:
    
    
  /api/Apps/:
    summary: End point to get all apps in the site
    description: Will get a json list object
    
    get:
      tags:
        - apps
      summary: Obtain details of all apps in the site
      description: Will have id, name, link, category, subcategory, points and logo
      operationId: getAppsById
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Apps'
        '400':
          description: incorrect input
          content:
            application/json:
              schema:
                type: object
                properties:
                  error_code:
                    type: string
                  error_message:
                    type: string
        default:
          description: Default error sample response
          
          
  /api/User/{username}/unregistered-apps/:
    summary: End point to get unregistered apps of a user
    description: username required
    
    get:
      tags:
        - apps
      summary: Obtain details of apps not registered by user
      description: username required
      operationId: getNotUserAppsById
      parameters:
        - in: path
          name: username
          required: True
          description: username of the user
          schema:
            type: string
            example: ram
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Apps'
        '400':
          description: incorrect input
          content:
            application/json:
              schema:
                type: object
                properties:
                  error_code:
                    type: string
                  error_message:
                    type: string
        default:
          description: Default error sample response
  
  /api/User/{username}/apps/:
    summary: End point to get registered apps of a user
    description: username required
    
    get:
      tags:
        - user_apps
      summary: Obtain details of apps already registered by user
      description: username required
      operationId: getUserAppsById
      parameters:
        - in: path
          name: username
          required: True
          description: username of the user
          schema:
            type: string
            example: ram
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserApps'
        '400':
          description: incorrect input
          content:
            application/json:
              schema:
                type: object
                properties:
                  error_code:
                    type: string
                  error_message:
                    type: string
        default:
          description: Default error sample response
  
    
    
  
    
  
          


components:
  schemas:
          
    App:
      description: Model containing app info
      properties:
        id:
          type: integer
          example: 4
        name:
          type: string
          example: Netflix
        link:
          type: string
          example: https://www.netflix.com
        category:
          type: string
          example: Entertainment
        subcategory:
          type: string
          example: OTT
        points:
          type: integer
          example: 150
        logo:
          type: string
          example: details of logo
   
    Apps:
      description: Array of appss
      type: array
      items:
        $ref: '#/components/schemas/App'
        
    UserApp:
      description: Model containing app info
      properties:
        id:
          type: integer
          example: 3
        uid:
          type: integer
          example: 5
        app:
          $ref: '#/components/schemas/App'
        registered_date:
          type: string
          example: 2023-01-16
        screenshot:
          type: string
          example: details of screenshot
    
    UserApps:
      description: Array of appss
      type: array
      items:
        $ref: '#/components/schemas/UserApp'